import type { Metadata } from 'next';

import { Navigation } from '@/components/commons';

export const metadata: Metadata = {
  title: { template: 'Next Movies | %s', default: 'Next Movies' },
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>
        <Navigation />

        {children}
      </body>
    </html>
  );
}
